"""add_summary_columns

Revision ID: 3f0f4f48aa41
Revises: 90fff2956014
Create Date: 2026-02-11 17:10:35.609594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f0f4f48aa41'
down_revision: Union[str, Sequence[str], None] = '90fff2956014'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('conversations', sa.Column('last_summarized_seq_id', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'last_summarized_seq_id')
    op.drop_column('conversations', 'summary')
    # ### end Alembic commands ###
