"""add_observability_columns

Revision ID: 90fff2956014
Revises: a4a37dd1410f
Create Date: 2026-02-11 16:58:33.101043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90fff2956014'
down_revision: Union[str, Sequence[str], None] = 'a4a37dd1410f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('token_count_prompt', sa.Integer(), nullable=True))
    op.add_column('messages', sa.Column('token_count_completion', sa.Integer(), nullable=True))
    op.add_column('messages', sa.Column('model', sa.String(), nullable=True))
    op.add_column('messages', sa.Column('latency_ms', sa.Integer(), nullable=True))
    op.add_column('messages', sa.Column('finish_reason', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'finish_reason')
    op.drop_column('messages', 'latency_ms')
    op.drop_column('messages', 'model')
    op.drop_column('messages', 'token_count_completion')
    op.drop_column('messages', 'token_count_prompt')
    # ### end Alembic commands ###
